<?php
defined( 'ABSPATH' ) || exit;

/**
 * WP-CLI: development-time generators.
 *
 * Replaces the previous behaviour of writing .scss files to disk on every
 * `init` (which broke on read-only deployments and silently went stale).
 * SCSS variables are a build-time artifact — regenerate them explicitly
 * whenever breakpoints change in stanza.json, then run the sass build.
 *
 *     wp stanza sync-scss
 */
if ( defined( 'WP_CLI' ) && WP_CLI ) {

	WP_CLI::add_command( 'stanza sync-scss', function () {
		$breakpoints = stanza_config()->settings->breakpoints ?? null;

		if ( empty( $breakpoints ) ) {
			WP_CLI::error( 'No settings.breakpoints found in the theme stanza.json.' );
		}

		$scss = "// Generated by `wp stanza sync-scss` — do not edit by hand.\n";
		foreach ( $breakpoints as $key => $value ) {
			$scss .= '$breakpoint-' . $key . ': ' . $value . ';' . PHP_EOL;
			$scss .= '$_breakpoint-' . $key . ': ' . ( str_replace( 'px', '', $value ) - 1 ) . 'px;' . PHP_EOL;
		}

		$targets = array( STANZA_PATH . 'variables.scss' );

		$theme_sass_dir = get_template_directory() . '/assets/src/sass';
		if ( is_dir( $theme_sass_dir ) ) {
			$targets[] = $theme_sass_dir . '/_stanza-variables.scss';
		}

		foreach ( $targets as $target ) {
			if ( file_put_contents( $target, $scss ) === false ) {
				WP_CLI::error( "Could not write {$target}" );
			}
			WP_CLI::log( "Wrote {$target}" );
		}

		WP_CLI::success( 'SCSS variables synced. Re-run your sass build to pick them up.' );
	} );
}
